### PR TITLE
Add sink config for NixOS

### PR DESCRIPTION
**Pull request by osandell**

### CODE REVIEW

**Review by lemmyg — CHANGES_REQUESTED** [review]
Could you please update your Nixos script to  copy directly the original config.
this way will be hard to maintain as your are duplicating the code.
Also I would not use fetchurl as files should be already available in the local git project.

**Comment by osandell** [comment]
> Could you please update your Nixos script to copy directly the original config. this way will be hard to maintain as your are duplicating the code. Also I would not use fetchurl as files should be already available in the local git project.

Yes, it would work to copy the .wav files from a local dir. But that would go against the idea of Nix wouldn't it? I wanted to make sure you have everything you need in the .nix files and it's ready to just build as is. As I understood the Nix philosophy it's that you should be able to very easily replicate the system with ideally just a set of .nix files.
 
But regarding using the original files I completely agree that it's much better to work with the originals. Only reason i did it like this is because I couldn't copy the originals as is, had to insert the dynamic path to the .wav files. But I'll change so it does this by patching instead.

**Comment by lemmyg** [comment]
If you want to download the wav file directly from the project is fine. It will always point to latest version but I should not be much problem.

**Comment by lemmyg** [comment]
Usually when you create a script that lives in the actual project, you just copy the local files.
if the script need to download any file would be because it lives in a separate project.
You could also store it in  your own Nixos project.

**Comment by osandell** [comment]
> Usually when you create a script that lives in the actual project, you just copy the local files. if the script need to download any file would be because it lives in a separate project. You could also store it in your own Nixos project. Is up to you. I would suggest to add note in the T2 Nixos wiki for other users

Cool! I've changed it so that it downloads the whole repo of a specific commit instead, then patches the conf file to insert the .wav:s.

**Review by lemmyg — APPROVED** [review]

**Pull request merged**
