### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lemmyg**
docs update

### CODE REVIEW

**Comment by sal4org** [comment]
Hi, GREAT work!

you should add to instalation instructions, that for fedora distro users, before running install.sh, it is needed that some dependencies must mandatory be installed:  sudo dnf install ladspa-swh-plugins pipewire-module-filter-chain-lv2

**Comment by lemmyg** [comment]
Hello,
thanks for your note. I'm not fedora user so I cant really test the installation.
If you could create a readme version with the fedora section. I'm happy to add it.

**Comment by sal4org** [comment]
hi,

update!

in mbp16,1 i9
there several others dependencies needed in fedora40 (lsp-plugins, lv2). the easy way is to just install: dnf install easyeffects. 

asap i will create a readme for fedora

**Comment by lemmyg** [comment]
perfect. Please try to follow the existing format. Thanks

**Pull request merged**
